/* ==========================================================================
netlify.toml

SPDX-License-Identifier: CC-BY-4.0 OR GPL-3.0-or-later
This file is part of Network Pro.
========================================================================== */

[build]
  command = "npm run build"
  publish = "build"
