# .github/workflows/build-and-publish.yml
#
# SPDX-License-Identifier: CC-BY-4.0 OR GPL-3.0-or-later
# This file is part of Network Pro

name: Build and Publish to Registries

on:
  release:
    types: [created]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  check-codeql:
    name: Check CodeQL Analysis
    runs-on: ubuntu-24.04
    # Continue workflow even if this job fails due to inability to find and/or check CodeQL workflow
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Check CodeQL Workflow Status
        uses: octokit/request-action@v2.4.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/${{ github.repository }}/actions/workflows/CodeQL.yml/runs
          query: |
            {
              "status": "success",
              "event": "push",
              "branch": "${{ github.ref_name }}"
            }

  build:
    needs: check-codeql
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: lts/*
          check-latest: true
          cache: npm

      - name: Cache Node.js modules
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-lts-${{ hashFiles('package-lock.json', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-lts-build-
            ${{ runner.os }}-node-lts-
            ${{ runner.os }}-

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build Node.js project
        run: npm run build

      # MkDocs Integration Begins
      #- name: Set up Python
      #  uses: actions/setup-python@v5.6.0
      #  with:
      #    python-version: "3.13"

      #- name: Install MkDocs and plugins
      #  run: |
      #    pip install mkdocs mkdocs-material mkdocs-rss-plugin

      # Strict mode temporarily disabled as workaround for mkdocs-material
      #- name: Build MkDocs documentation
      #  run: mkdocs build
      # MkDocs Integration Ends

      - name: Copy package.json to build directory
        run: cp package.json build/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: site-build-${{ github.run_id }}
          path: ./build

  publish:
    needs: [check-codeql, build]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
        registry: ["npmjs", "gpr"]

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: site-build-${{ github.run_id }}

      - name: Login to registry
        run: |
          if [[ "${{ matrix.registry }}" == "npmjs" ]]; then
            npm login --registry=https://registry.npmjs.org/ --scope=@networkpro --always-auth --username "sundevil311" --authToken ${{ secrets.NPM_NETPRO }}
          else
            npm login --registry=https://npm.pkg.github.com/ --scope=@netwk-pro --always-auth --username "sundevil311" --authToken ${{ secrets.GITHUB_TOKEN }}
          fi

      - name: Set up Git user
        run: |
          git config --global user.email "github@sl.neteng.cc"
          git config --global user.name "SunDevil311"

      - name: Update package name for GPR
        if: matrix.registry == 'gpr'
        run: |
          sed -i 's/"name": ".*"/"name": "@netwk-pro\/web"/' build/package.json

      - name: Publish package
        working-directory: ./build
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_NETPRO if matrix.registry == 'npmjs' else secrets.GITHUB_TOKEN }}
